// todomvc-angular/src/app/TodoList/todo-list.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: `TodoList`,
    template:`<ul><Todo *ngFor="let t of todos" class="{{showDone ? '' : 'hide-done'}}" [text]="t.text" [done]="t.done"></Todo></ul>`
})
export default class TodoListComponent {
    @Input() todos : any[];
    @Input() showDone : boolean;
}

// todomvc-react/src/components/TodoList.jsx
import React from 'react';
import { connect } from 'react-redux';

const TodoList = ({todos,showDone,toggleTodoDone})=>(
    <ul>
        {todos
            .filter(todo=>!todo.done || showDone)
            .map((todo,i)=>(
            <li key={i}>
                {todo.text}
                <input type="checkbox" onChange={()=>toggleTodoDone(todo)} checked={todo.done}/>
            </li>
        ))}
    </ul>
);

const mapStateToProps = (state)=> ({
    todos: state.todos,
    showDone: state.showDone
});

const mapDispatchToProps = (dispatch)=>({
    toggleTodoDone(todo){
        const updated = {...todo,done:!todo.done};
        dispatch({type:"UPDATE_TODO",todo:updated});
    }
});

export default connect(mapStateToProps, mapDispatchToProps)(TodoList);
